# coding: UTF-8

extension_id = {
    "Ada": 19,
    "Algol 68": 70,
    "Assembly (32bit)": 27,
    "Assembly (64bit)": 87,
    "awk": 21,
    "Bash": 5,
    "bc": 48,
    "Befunge": 71,
    "Boo": 46,
    "Brainfuck": 23,
    "C (Clang)": 59,
    "C": 0,
    "C# 6.0": 62,
    "C++ (Clang)": 60,
    "C++": 1,
    "C++11 (Clang)": 66,
    "C++11": 49,
    "C++14 (Clang)": 67,
    "C++14": 88,
    "C++17 (Clang)": 85,
    "C++17": 84,
    "C11 (Clang)": 77,
    "C11": 75,
    "Cobol": 35,
    "Cobra": 54,
    "D": 29,
    "F#": 37,
    "Fortran": 13,
    "Go": 12,
    "Golfscript": 79,
    "Haxe": 81,
    "Intercal": 47,
    "Java (OpenJDK)": 91,
    "Java 11": 93,
    "Java": 3,
    "Kotlin (JVM)": 69,
    "Kotlin (Native)": 92,
    "LOLCODE": 82,
    "Lua": 16,
    "Nemerle": 53,
    "node.js": 17,
    "Objective-C": 10,
    "Objective-C++": 64,
    "OCaml": 22,
    "Pascal": 2,
    "Perl": 8,
    "PHP": 7,
    "Pike": 41,
    "PyPy2": 32,
    "PyPy3": 73,
    "Python 2": 6,
    "Python 3": 28,
    "R": 72,
    "Rhino": 34,
    "Ruby 2.5": 68,
    "Rust": 44,
    "Scheme": 14,
    "sed": 43,
    "Swift": 74,
    "Tcl": 26,
    "Text": 58,
    "VB.NET 4.0": 63,
    "Whitespace": 24,
    "아희": 83
}

extension_name = {
    "Ada": 'ada',
    "Algol 68": 'a68',
    "Assembly (32bit)": '32b.asm',
    "Assembly (64bit)": '64b.asm',
    "awk": 'awk',
    "Bash": 'sh',
    "bc": 'bc',
    "Befunge": 'befunge.bf',
    "Boo": 'boo',
    "Brainfuck": 'bf',
    "C (Clang)": 'clang.c',
    "C": 'c',
    "C# 6.0": 'cs',
    "C++ (Clang)": 'clang.cpp',
    "C++": 'cpp',
    "C++11 (Clang)": 'clang_pp11.cpp',
    "C++11": 'cpp11.cpp',
    "C++14 (Clang)": 'clang_pp14.cpp',
    "C++14": 'cpp14.cpp',
    "C++17 (Clang)": 'clang_pp17.cpp',
    "C++17": 'cpp17.cpp',
    "C11 (Clang)": 'clang11.c',
    "C11": 'c11.c',
    "Clojure": 'clj',
    "Cobol": 'cob',
    "Cobra": 'cobra',
    "D": 'd',
    "F#": 'fs',
    "Fortran": 'f95',
    "FreeBASIC": 'bas',
    "Go": 'go',
    "Golfscript": 'gs',
    "Gosu": 'gsp',
    "Haxe": 'haxe.py',
    "Intercal": 'i',
    "Java (OpenJDK)": 'openjdk.java',
    "Java 11": 'j11.java',
    "Java": 'java',
    "Kotlin (JVM)": 'jvm.kt',
    "Kotlin (Native)": 'nat.kt',
    "LOLCODE": 'lol',
    "Lua": 'lua',
    "Nemerle": 'n',
    "Nimrod": 'nim',
    "node.js": 'js',
    "Objective-C": 'm',
    "Objective-C++": 'mm',
    "OCaml": 'ml',
    "Pascal": 'pas',
    "Perl": 'pl',
    "PHP": 'php',
    "Pike": 'pike',
    "PyPy2": 'pypy.py',
    "PyPy3": 'pypy3.py',
    "Python 2": 'py2.py',
    "Python 3": 'py3.py',
    "R": 'R',
    "Rhino": 'rhino.js',
    "Ruby 2.5": 'rb',
    "Rust": 'rs',
    "Scheme": 'scm',
    "sed": 'sed',
    "SpiderMonkey": 'spider.js',
    "Swift": 'swift',
    "Tcl": 'tcl',
    "Text": 'txt',
    "VB.NET 4.0": 'vb',
    "Whitespace": 'ws',
    "아희": 'aheui'
}
